# (c) Copyright 2019-2023 OLX
[package]
name = "libvips-bindings"
description = "Safe bindings for libvips"
version = "0.0.3"
authors = ["Augusto César Dias <augusto.c.dias@gmail.com>"]
repository = "https://github.com/augustocdias/libvips-rust-bindings"
edition = "2021"

[build-dependencies]
bindgen = "0.68.1"
Inflector = "0.11"
cc = "1.0"
which = "5.0"

[dependencies]
num-traits = "0.2"
num-derive = "0.4"
